# Generated by Django 6.0.6 on 2026-06-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=200, verbose_name="first name")),
                ("middle_name", models.CharField(blank=True, max_length=200, null=True, verbose_name="middle name")),
                ("surname", models.CharField(blank=True, max_length=200, verbose_name="surname")),
                ("id_number", models.CharField(blank=True, max_length=200, verbose_name="id number")),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("id_card", "ID Card"),
                            ("passport", "Passport"),
                            ("driver_license", "Driver's License"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="id type",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=200, verbose_name="phone number")),
                ("email", models.CharField(blank=True, max_length=200, verbose_name="email")),
                ("address", models.CharField(blank=True, max_length=200, verbose_name="address")),
                (
                    "skoufas_member_id",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Skoufas member ID"),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["surname", "middle_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("surname", "middle_name", "first_name", "phone_number"), name="unique_name_and_number"
                    ),
                    models.UniqueConstraint(fields=("id_type", "id_number"), name="unique_id_document"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("start", models.DateField(verbose_name="start")),
                ("expected_end", models.DateField(verbose_name="expected end")),
                ("end", models.DateField(blank=True, null=True, verbose_name="end")),
                ("note", models.CharField(blank=True, max_length=4096, verbose_name="note")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loaning.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "entry_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.entrynumber", verbose_name="Entry number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["status", "end", "expected_end", "entry_number", "customer"],
            },
        ),
    ]
