exclude: .*/migrations/.*|venv|junk
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: check-shebang-scripts-are-executable

  - repo: local
    hooks:
      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: mypy
        name: Run type checks
        entry: mypy
        language: system
        types: [python]
        args:
          ["--ignore-missing-imports", "--install-types", "--non-interactive"]
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: bash -c "./manage.py makemigrations --check --dry-run"
        types: ["python"]
        pass_filenames: false
