"""
List of valid dewey classes.

Based on https://en.wikipedia.org/wiki/List_of_Dewey_Decimal_classes .
"""
# flake8: noqa: E501
from typing import Optional

from django.utils.functional import Promise as StrPromise
from django.utils.translation import gettext_lazy as _


CLASSIFICATION_CLASSES = {
    0: _("Computer science, information and general works"),
    1: _("Philosophy and psychology"),
    2: _("Religion"),
    3: _("Social sciences"),
    4: _("Language"),
    5: _("Science"),
    6: _("Technology"),
    7: _("Arts and recreation"),
    8: _("Literature"),
    9: _("History and geography"),
}

CLASSIFICATION_SUB_CLASSES = {
    0: _("Computer science, knowledge and systems"),
    10: _("Bibliographies"),
    20: _("Library and information sciences"),
    30: _("Encyclopedias and books of facts"),
    40: _("Unassigned (formerly Biographies)"),
    50: _("Magazines, journals and serials"),
    60: _("Associations, organizations and museums"),
    70: _("News media, journalism and publishing"),
    80: _("Quotations"),
    90: _("Manuscripts and rare books"),
    100: _("Philosophy"),
    110: _("Metaphysics"),
    120: _("Epistemology"),
    130: _("Parapsychology and occultism"),
    140: _("Philosophical schools of thought"),
    150: _("Psychology"),
    160: _("Philosophical logic"),
    170: _("Ethics"),
    180: _("Ancient, medieval, and Eastern philosophy"),
    190: _("Modern Western philosophy (19th-century, 20th-century)"),
    200: _("Religion"),
    210: _("Philosophy and theory of religion"),
    220: _("The Bible"),
    230: _("Christianity"),
    240: _("Christian practice and observance"),
    250: _("Christian orders and local church"),
    260: _("Social and ecclesiastical theology"),
    270: _("History of Christianity"),
    280: _("Christian denominations"),
    290: _("Other religions"),
    300: _("Social sciences, sociology and anthropology"),
    310: _("Statistics"),
    320: _("Political science"),
    330: _("Economics"),
    340: _("Law"),
    350: _("Public administration and military science"),
    360: _("Social problems and social services"),
    370: _("Education"),
    380: _("Commerce, communications and transportation"),
    390: _("Customs, etiquette and folklore"),
    400: _("Language"),
    410: _("Linguistics"),
    420: _("English and Old English languages"),
    430: _("German and related languages"),
    440: _("French and related languages"),
    450: _("Italian, Romanian and related languages"),
    460: _("Spanish, Portuguese, Galician"),
    470: _("Latin and Italic languages"),
    480: _("Classical and modern Greek languages"),
    490: _("Other languages"),
    500: _("Science"),
    510: _("Mathematics"),
    520: _("Astronomy"),
    530: _("Physics"),
    540: _("Chemistry"),
    550: _("Earth sciences and geology"),
    560: _("Fossils and prehistoric life"),
    570: _("Biology"),
    580: _("Plants"),
    590: _("Animals (Zoology)"),
    600: _("Technology"),
    610: _("Medicine and health"),
    620: _("Engineering"),
    630: _("Agriculture"),
    640: _("Home and family management"),
    650: _("Management and public relations"),
    660: _("Chemical engineering"),
    670: _("Manufacturing"),
    680: _("Manufacture for specific uses"),
    690: _("Construction of buildings"),
    700: _("Arts"),
    710: _("Area planning and landscape architecture"),
    720: _("Architecture"),
    730: _("Sculpture, ceramics and metalwork"),
    740: _("Graphic arts and decorative arts"),
    750: _("Painting"),
    760: _("Printmaking and prints"),
    770: _("Photography, computer art, film, video"),
    780: _("Music"),
    790: _("Outline of sports, games and entertainment"),
    800: _("Literature, rhetoric and criticism"),
    810: _("American literature in English"),
    820: _("English and Old English literatures"),
    830: _("German and related literatures"),
    840: _("French and related literatures"),
    850: _("Italian, Romanian and related literatures"),
    860: _("Spanish, Portuguese, Galician literatures"),
    870: _("Latin and Italic literatures"),
    880: _("Classical and modern Greek literatures"),
    890: _("Other literatures"),
    900: _("History"),
    910: _("Geography and travel"),
    920: _("Biography and genealogy"),
    930: _("History of ancient world (to c. 499)"),
    940: _("History of Europe"),
    950: _("History of Asia"),
    960: _("History of Africa"),
    970: _("History of North America"),
    980: _("History of South America"),
    990: _("History of other areas"),
}

CLASSIFICATION_DECIMAL_CLASSES = {
    0: _("Computer science, information and general works"),
    1: _("Knowledge"),
    2: _("The book (writing, libraries, and book-related topics)"),
    3: _("Systems"),
    4: _("Data processing and computer science"),
    5: _("Computer programming, programs and data"),
    6: _("Special computer methods (e.g. AI, multimedia, VR)[4]"),
    7: _("[Unassigned]"),
    8: _("[Unassigned]"),
    9: _("[Unassigned]"),
    10: _("Bibliography"),
    11: _("Bibliographies"),
    12: _("Bibliographies of individuals"),
    13: _("[Unassigned]"),
    14: _("Bibliographies of anonymous and pseudonymous works"),
    15: _("Bibliographies of works from specific places"),
    16: _("Bibliographies of works on specific subjects"),
    17: _("General subject catalogs"),
    18: _("Catalogs arranged by author, date, etc."),
    19: _("Dictionary catalogs"),
    20: _("Library and information sciences"),
    21: _("Library relationships (with archives, information centers, etc.)"),
    22: _("Administration of physical plant"),
    23: _("Personnel management"),
    24: _("[Unassigned]"),
    25: _("Library operations"),
    26: _("Libraries for specific subjects"),
    27: _("General libraries"),
    28: _("Reading and use of other information media"),
    29: _("[Unassigned]"),
    30: _("General encyclopedic works"),
    31: _("Encyclopedias in American English"),
    32: _("Encyclopedias in English"),
    33: _("Encyclopedias in other Germanic languages"),
    34: _("Encyclopedias in French, Occitan, and Catalan"),
    35: _("Encyclopedias in Italian, Romanian, and related languages"),
    36: _("Encyclopedias in Spanish and Portuguese"),
    37: _("Encyclopedias in Slavic languages"),
    38: _("Encyclopedias in Scandinavian languages"),
    39: _("Encyclopedias in other languages"),
    50: _("General serial publications"),
    51: _("Serials in American English"),
    52: _("Serials in English"),
    53: _("Serials in other Germanic languages"),
    54: _("Serials in French, Occitan, and Catalan"),
    55: _("Serials in Italian, Romanian, and related languages"),
    56: _("Serials in Spanish and Portuguese"),
    57: _("Serials in Slavic languages"),
    58: _("Serials in Scandinavian languages"),
    59: _("Serials in other languages"),
    60: _("General organizations and museum science"),
    61: _("Organizations in North America"),
    62: _("Organizations in British Isles; in England"),
    63: _("Organizations in central Europe; in Germany"),
    64: _("Organizations in France and Monaco"),
    65: _("Organizations in Italy and adjacent islands"),
    66: _("Organizations in Iberian peninsula and adjacent islands"),
    67: _("Organizations in eastern Europe; in Russia"),
    68: _("Organizations in other geographic areas"),
    69: _("Museum science"),
    70: _("News media, journalism, and publishing"),
    71: _("Newspapers in North America"),
    72: _("Newspapers in British Isles; in England"),
    73: _("Newspapers in central Europe; in Germany"),
    74: _("Newspapers in France and Monaco"),
    75: _("Newspapers in Italy and adjacent islands"),
    76: _("Newspapers in Iberian peninsula and adjacent islands"),
    77: _("Newspapers in eastern Europe; in Russia"),
    78: _("Newspapers in Scandinavia"),
    79: _("Newspapers in other geographic areas"),
    80: _("General collections"),
    81: _("Collections in American English"),
    82: _("Collections in English"),
    83: _("Collections in other Germanic languages"),
    84: _("Collections in French, Occitan, Catalan"),
    85: _("Collections in Italian, Romanian, and related languages"),
    86: _("Collections in Spanish and Portuguese"),
    87: _("Collections in Slavic languages"),
    88: _("Collections in Scandinavian languages"),
    89: _("Collections in other languages"),
    90: _("Manuscripts and rare books"),
    91: _("Manuscripts"),
    92: _("Block books"),
    93: _("Incunabula"),
    94: _("Printed books"),
    95: _("Books notable for bindings"),
    96: _("Books notable for illustrations"),
    97: _("Books notable for ownership or origin"),
    98: _("Prohibited works, forgeries, and hoaxes"),
    99: _("Books notable for format"),
    100: _("Philosophy and psychology"),
    101: _("Theory of philosophy"),
    102: _("Miscellany"),
    103: _("Dictionaries and encyclopedias"),
    104: _("No longer used — formerly Essays"),
    105: _("Serial publications"),
    106: _("Organizations and management"),
    107: _("Education, research, related topics of philosophy"),
    108: _("Groups of people"),
    109: _("History and collected biography"),
    110: _("Metaphysics"),
    111: _("Ontology"),
    112: _("No longer used — formerly Methodology"),
    113: _("Cosmology (Philosophy of nature)"),
    114: _("Space"),
    115: _("Time"),
    116: _("Change"),
    117: _("Structure"),
    118: _("Force and energy"),
    119: _("Number and quantity"),
    120: _("Epistemology, causation, and humankind"),
    121: _("Epistemology (Theory of knowledge)"),
    122: _("Causation"),
    123: _("Determinism and indeterminism"),
    124: _("Teleology"),
    125: _("No longer used — formerly Infinity"),
    126: _("The self"),
    127: _("The unconscious and the subconscious"),
    128: _("Humankind"),
    129: _("Origin and destiny of individual souls"),
    130: _("Parapsychology and occultism"),
    131: _("Parapsychological and occult methods for achieving well-being, happiness, success"),
    132: _("No longer used — formerly Mental derangements"),
    133: _("Specific topics in parapsychology and occultism"),
    134: _("No longer used — formerly Mesmerism and Clairvoyance"),
    135: _("Dreams and mysteries"),
    136: _("No longer used — formerly Mental characteristics"),
    137: _("Divinatory graphology"),
    138: _("Physiognomy"),
    139: _("Phrenology"),
    140: _("Specific philosophical schools and viewpoints"),
    141: _("Idealism and related systems and doctrines"),
    142: _("Critical philosophy"),
    143: _("Bergsonism and intuitionism"),
    144: _("Humanism and related systems and doctrines"),
    145: _("Sensationalism"),
    146: _("Naturalism and related systems and doctrines"),
    147: _("Pantheism and related systems and doctrines"),
    148: _("Dogmatism, eclecticism, liberalism, syncretism, and traditionalism"),
    149: _("Other philosophical systems and doctrines"),
    150: _("Psychology"),
    151: _("No longer used — formerly Intellect"),
    152: _("Sensory perception, movement, emotions, and physiological drives"),
    153: _("Conscious mental processes and intelligence"),
    154: _("Subconscious and altered states and processes"),
    155: _("Differential and developmental psychology"),
    156: _("Comparative psychology"),
    157: _("No longer used — formerly Emotions"),
    158: _("Applied psychology"),
    159: _("No longer used — formerly Will"),
    160: _("Philosophical logic"),
    161: _("Induction"),
    162: _("Deduction"),
    163: _("Not assigned or no longer used"),
    164: _("Not assigned or no longer used"),
    165: _("Fallacies and sources of error"),
    166: _("Syllogisms"),
    167: _("Hypotheses"),
    168: _("Argument and persuasion"),
    169: _("Analogy"),
    170: _("Ethics (Moral philosophy)"),
    171: _("Ethical systems"),
    172: _("Political ethics"),
    173: _("Ethics of family relationships"),
    174: _("Occupational ethics"),
    175: _("Ethics of recreation, leisure, public performances, communication"),
    176: _("Ethics of sex and reproduction"),
    177: _("Ethics of social relations"),
    178: _("Ethics of consumption"),
    179: _("Other ethical norms"),
    180: _("Ancient, medieval, eastern philosophy"),
    181: _("Eastern philosophy"),
    182: _("Pre-Socratic Greek philosophies"),
    183: _("Sophistic, Socratic, related Greek philosophies"),
    184: _("Platonic philosophy"),
    185: _("Aristotelian philosophy"),
    186: _("Skeptic and Neoplatonic philosophies"),
    187: _("Epicurean philosophy"),
    188: _("Stoic philosophy"),
    189: _("Medieval Western philosophy"),
    190: _("Modern Western and other noneastern philosophy"),
    191: _("Philosophy of the United States and Canada"),
    192: _("Philosophy of the British Isles"),
    193: _("Philosophy of Germany and Austria"),
    194: _("Philosophy of France"),
    195: _("Philosophy of Italy"),
    196: _("Philosophy of Spain and Portugal"),
    197: _("Philosophy of Russia"),
    198: _("Philosophy of Scandinavia and Finland"),
    199: _("Philosophy in other geographic areas"),
    200: _("Religion"),
    201: _("Religious mythology, general classes of religion, interreligious relations and attitudes, social theology"),
    202: _("Doctrines"),
    203: _("Public worship and other practices"),
    204: _("Religious experience, life, practice"),
    205: _("Religious ethics"),
    206: _("Leaders and organization"),
    207: _("Missions and religious education"),
    208: _("Sources"),
    209: _("Sects and reform movements"),
    210: _("Philosophy and theory of religion"),
    211: _("Concepts of God"),
    212: _("Existence, ways of knowing God, attributes of God"),
    213: _("Creation"),
    214: _("Theodicy"),
    215: _("Science and religion"),
    216: _("No longer used—formerly Evil"),
    217: _("No longer used—formerly Prayer"),
    218: _("Humankind"),
    219: _("No longer used—formerly Analogies"),
    220: _("Bible"),
    221: _("Old Testament (Tanakh)"),
    222: _("Historical books of Old Testament"),
    223: _("Poetic books of Old Testament"),
    224: _("Prophetic books of Old Testament"),
    225: _("New Testament"),
    226: _("Gospels and Acts"),
    227: _("Epistles"),
    228: _("Revelation (Apocalypse)"),
    229: _("Apocrypha, pseudepigrapha, and inter-testamental works"),
    230: _("Christianity"),
    231: _("God"),
    232: _("Jesus Christ and his family"),
    233: _("Humankind"),
    234: _("Salvation and grace"),
    235: _("Spiritual beings"),
    236: _("Eschatology"),
    237: _("No longer used—formerly Future state"),
    238: _("Creeds, confessions of faith, covenants, and catechisms"),
    239: _("Apologetics and polemics"),
    240: _("Christian moral and devotional theology"),
    241: _("Christian ethics"),
    242: _("Devotional literature"),
    243: _("Evangelistic writings for individuals and families"),
    244: _("No longer used—formerly Religious fiction"),
    245: _("No longer used—formerly Hymnology"),
    246: _("Use of art in Christianity"),
    247: _("Church furnishings and related articles"),
    248: _("Christian experience, practice, life"),
    249: _("Christian observances in family life"),
    250: _("Local Christian church and Christian religious orders"),
    251: _("Preaching (Homiletics)"),
    252: _("Texts of sermons"),
    253: _("Pastoral office and work (Pastoral theology)"),
    254: _("Parish administration"),
    255: _("Religious congregations and orders"),
    256: _("No longer used — formerly Religious societies"),
    257: _("No longer used — formerly Parochial schools, libraries, etc."),
    258: _("No longer used — formerly Parochial medicine"),
    259: _("Pastoral care of families, of specific groups of people"),
    260: _("Christian social and ecclesiastical theology"),
    261: _("Social theology and interreligious relations and attitudes"),
    262: _("Ecclesiology"),
    263: _("Days, times, places of religious observance"),
    264: _("Public worship"),
    265: _("Sacraments, other rites and acts"),
    266: _("Missions"),
    267: _("Associations for religious work"),
    268: _("Religious education"),
    269: _("Spiritual renewal"),
    270: _("History, geographic treatment, biography of Christianity"),
    271: _("Religious congregations and orders in church history"),
    272: _("Persecutions in church history"),
    273: _("Doctrinal controversies and heresies in general church history"),
    274: _("Christianity in Europe"),
    275: _("Christianity in Asia"),
    276: _("Christianity in Africa"),
    277: _("Christianity in North America"),
    278: _("Christianity in South America"),
    279: _("History of Christianity in other areas"),
    280: _("Denominations and sects of Christian church"),
    281: _("Early church and Eastern churches"),
    282: _("Roman Catholic Church"),
    283: _("Anglican churches"),
    284: _("Protestant denominations of Continental origin and related body"),
    285: _("Presbyterian churches, Reformed churches centered in America, Congregational churches"),
    286: _("Baptist, Restoration Movement, Adventist churches"),
    287: _("Methodist churches; churches related to Methodism"),
    288: _("No longer used — formerly Unitarian"),
    289: _("Other denominations and sects"),
    290: _("Other religions"),
    291: _("No longer used — formerly Comparative religion"),
    292: _("Classical religion (Greek and Roman religion)"),
    293: _("Germanic religion"),
    294: _("Religions of Indic origin"),
    295: _("Zoroastrianism (Mazdaism, Parseeism)"),
    296: _("Judaism"),
    297: _("Islam, Bábism and Baháʼí Faith"),
    298: _("No longer used — formerly Mormonism"),
    299: _("Religions not provided for elsewhere"),
    300: _("Social sciences"),
    301: _("Sociology and anthropology"),
    302: _("Social interaction"),
    303: _("Social processes"),
    304: _("Factors affecting social behavior"),
    305: _("Groups of people"),
    306: _("Culture and institutions"),
    307: _("Communities"),
    308: _("No longer used — formerly Polygraphy"),
    309: _("No longer used — formerly History of sociology"),
    310: _("Collections of general statistics"),
    311: _("No longer used — formerly Theory and methods"),
    312: _("No longer used — formerly Population"),
    313: _("No longer used — formerly Special topics"),
    314: _("General statistics of Europe"),
    315: _("General statistics of Asia"),
    316: _("General statistics of Africa"),
    317: _("General statistics of North America"),
    318: _("General statistics of South America"),
    319: _(
        "General statistics of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica"
    ),
    320: _("Political science (Politics and government)"),
    321: _("Systems of governments and states"),
    322: _("Relation of state to organized groups and their members"),
    323: _("Civil and political rights"),
    324: _("The political process"),
    325: _("International migration and colonization"),
    326: _("Slavery and emancipation"),
    327: _("International relations"),
    328: _("The legislative process"),
    329: _("Not assigned or no longer used"),
    330: _("Economics"),
    331: _("Labor economics"),
    332: _("Financial economics"),
    333: _("Economics of land and energy"),
    334: _("Cooperatives"),
    335: _("Socialism and related systems"),
    336: _("Public finance"),
    337: _("International economics"),
    338: _("Production"),
    339: _("Macroeconomics and related topics"),
    340: _("Law"),
    341: _("Law of nations"),
    342: _("Constitutional and administrative law"),
    343: _("Military, defense, public property, public finance, tax, commerce (trade), industrial law"),
    344: _("Labor, social service, education, cultural law"),
    345: _("Criminal law"),
    346: _("Private law"),
    347: _("Procedure and courts"),
    348: _("Laws, regulations, cases"),
    349: _("Law of specific jurisdictions, areas, socioeconomic regions, regional intergovernmental organizations"),
    350: _("Public administration and military science"),
    351: _("Public administration"),
    352: _("General considerations of public administration"),
    353: _("Specific fields of public administration"),
    354: _("Public administration of economy and environment"),
    355: _("Military science"),
    356: _("Foot forces and warfare"),
    357: _("Mounted forces and warfare"),
    358: _("Air and other specialized forces and warfare; engineering and related services"),
    359: _("Sea forces and warfare"),
    360: _("Social problems and services; associations"),
    361: _("Social problems and services"),
    362: _("Social problems of and services to groups of people"),
    363: _("Other social problems and services"),
    364: _("Criminology"),
    365: _("Penal and related institutions"),
    366: _("Secret associations and societies"),
    367: _("General clubs"),
    368: _("Insurance"),
    369: _("Associations"),
    370: _("Education"),
    371: _("Schools and their activities, special education"),
    372: _("Primary education (elementary education)"),
    373: _("Secondary education"),
    374: _("Adult education"),
    375: _("Curricula"),
    376: _("No longer used — formerly Education of women"),
    377: _("No longer used — formerly Ethical education"),
    378: _("Higher education (Tertiary education)"),
    379: _("Public policy issues in education"),
    380: _("Commerce, communications transportation"),
    381: _("Commerce (Trade)"),
    382: _("International commerce (Foreign trade)"),
    383: _("Postal communication"),
    384: _("Communications"),
    385: _("Railroad transportation"),
    386: _("Inland waterway and ferry transportation"),
    387: _("Water, air, space transportation"),
    388: _("Transportation"),
    389: _("Metrology and standardization"),
    390: _("Customs, etiquette, folklore"),
    391: _("Costume and personal appearance"),
    392: _("Customs of life cycle and domestic life"),
    393: _("Death customs"),
    394: _("General customs"),
    395: _("Etiquette (Manners)"),
    396: _("No longer used — formerly Women's position and treatment"),
    397: _("No longer used — formerly outcast studies"),
    398: _("Folklore"),
    399: _("Customs of war and diplomacy"),
    400: _("Language"),
    401: _("Philosophy and theory, international languages"),
    402: _("Miscellany"),
    403: _("Dictionaries, encyclopedias, concordances"),
    404: _("Special topics of language"),
    405: _("Serial publications"),
    406: _("Organizations and management"),
    407: _("Education, research, related topics"),
    408: _("Groups of people"),
    409: _("Geographic treatment and biography"),
    410: _("Linguistics"),
    411: _("Writing systems of standard forms of languages"),
    412: _("Etymology of standard forms of languages"),
    413: _("Dictionaries of standard forms of languages"),
    414: _("Phonology and phonetics of standard forms of languages"),
    415: _("Grammar of standard forms of languages"),
    416: _("No longer used — formerly Prosody"),
    417: _("Dialectology and historical linguistics"),
    418: _("Standard usage (Prescriptive linguistics)"),
    419: _("Sign languages"),
    420: _("English and Old English (Anglo-Saxon)"),
    421: _("Writing system, phonology, phonetics of standard English"),
    422: _("Etymology of standard English"),
    423: _("Dictionaries of standard English"),
    424: _("No longer used — formerly English thesauruses"),
    425: _("Grammar of standard English"),
    426: _("No longer used — formerly English prosodies"),
    427: _("Historical and geographical variations, modern nongeographic variations of English"),
    428: _("Standard English usage (Prescriptive linguistics)"),
    429: _("Old English (Anglo-Saxon)"),
    430: _("German and related languages"),
    431: _("Writing systems, phonology, phonetics of standard German"),
    432: _("Etymology of standard German"),
    433: _("Dictionaries of standard German"),
    434: _("Not assigned or no longer used"),
    435: _("Grammar of standard German"),
    436: _("Not assigned or no longer used"),
    437: _("Historical and geographic variations, modern nongeographic variations of German"),
    438: _("Standard German usage (Prescriptive linguistics)"),
    439: _("Other Germanic languages"),
    440: _("French and related Romance languages"),
    441: _("Writing systems, phonology, phonetics of standard French"),
    442: _("Etymology of standard French"),
    443: _("Dictionaries of standard French"),
    444: _("Not assigned or no longer used"),
    445: _("Grammar of standard French"),
    446: _("Not assigned or no longer used"),
    447: _("Historical and geographic variations, modern nongeographic variations of French"),
    448: _("Standard French usage (Prescriptive linguistics)"),
    449: _("Occitan Catalan, Franco-Provençal"),
    450: _("Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican"),
    451: _("Writing systems, phonology, phonetics of standard Italian"),
    452: _("Etymology of standard Italian"),
    453: _("Dictionaries of standard Italian"),
    454: _("Not assigned or no longer used"),
    455: _("Grammar of standard Italian"),
    456: _("Not assigned or no longer used"),
    457: _("Historical and geographic variations, modern nongeographic variations of Italian"),
    458: _("Standard Italian usage (Prescriptive linguistics)"),
    459: _("Romanian, Rhaetian, Sardinian, Corsican"),
    460: _("Spanish, Portuguese, Galician"),
    461: _("Writing systems, phonology, phonetics of standard Spanish"),
    462: _("Etymology of standard Spanish"),
    463: _("Dictionaries of standard Spanish"),
    464: _("Not assigned or no longer used"),
    465: _("Grammar of standard Spanish"),
    466: _("Not assigned or no longer used"),
    467: _("Historical and geographic variations, modern nongeographic variations of Spanish"),
    468: _("Standard Spanish usage (Prescriptive linguistics)"),
    469: _("Portuguese"),
    470: _("Latin and related Italic languages"),
    471: _("Writing systems, phonology, phonetics of classical Latin"),
    472: _("Etymology of classical Latin"),
    473: _("Dictionaries of classical Latin"),
    474: _("Not assigned or no longer used"),
    475: _("Grammar of classical Latin"),
    476: _("Not assigned or no longer used"),
    477: _("Old, postclassical, Vulgar Latin"),
    478: _("Classical Latin usage (Prescriptive linguistics)"),
    479: _("Other Italic languages"),
    480: _("Classical Greek and related Hellenic languages"),
    481: _("Writing systems, phonology, phonetics of classical Greek"),
    482: _("Etymology of classical Greek"),
    483: _("Dictionaries of classical Greek"),
    484: _("Not assigned or no longer used"),
    485: _("Grammar of classical Greek"),
    486: _("Not assigned or no longer used"),
    487: _("Preclassical and postclassical Greek"),
    488: _("Classical Greek usage (Prescriptive linguistics)"),
    489: _("Other Hellenic languages"),
    490: _("Other languages"),
    491: _("East Indo-European and Celtic languages"),
    492: _("Afro-Asiatic languages"),
    493: _("Non-Semitic Afro-Asiatic languages"),
    494: _("Altic, Uralic, Hyperborean, Dravidian languages, miscellaneous languages of south Asia"),
    495: _("Languages of East and Southeast Asia"),
    496: _("African languages"),
    497: _("North American native languages"),
    498: _("South American native languages"),
    499: _("Non-Austronesian languages of Oceania, Austronesian languages, miscellaneous languages"),
    500: _("Natural sciences and mathematics"),
    501: _("Philosophy and theory"),
    502: _("Miscellany"),
    503: _("Dictionaries, encyclopedias, concordances"),
    504: _("Not assigned or no longer used"),
    505: _("Serial publications"),
    506: _("Organizations and management"),
    507: _("Education, research, related topics"),
    508: _("Natural history"),
    509: _("History, geographic treatment, biography"),
    510: _("Mathematics"),
    511: _("General principles of mathematics"),
    512: _("Algebra"),
    513: _("Arithmetic"),
    514: _("Topology"),
    515: _("Analysis"),
    516: _("Geometry"),
    517: _("Not assigned or no longer used"),
    518: _("Numerical analysis"),
    519: _("Probabilities and applied mathematics"),
    520: _("Astronomy and allied sciences"),
    521: _("Celestial mechanics"),
    522: _("Techniques, procedures, apparatus, equipment, materials"),
    523: _("Specific celestial bodies and phenomena"),
    524: _("Not assigned or no longer used"),
    525: _("Earth (Astronomical geography)"),
    526: _("Mathematical geography"),
    527: _("Celestial navigation"),
    528: _("Ephemerides"),
    529: _("Chronology"),
    530: _("Physics"),
    531: _("Classical mechanics"),
    532: _("Fluid mechanics"),
    533: _("Pneumatics (Gas mechanics)"),
    534: _("Sound and related vibrations"),
    535: _("Light and related radiation"),
    536: _("Heat"),
    537: _("Electricity and electronics"),
    538: _("Magnetism"),
    539: _("Modern physics"),
    540: _("Chemistry and allied sciences"),
    541: _("Physical chemistry"),
    542: _("Techniques, procedures, apparatus, equipment, materials"),
    543: _("Analytical chemistry"),
    544: _("No longer used — formerly Qualitative analysis"),
    545: _("No longer used — formerly Quantitative analysis"),
    546: _("Inorganic chemistry"),
    547: _("Organic chemistry"),
    548: _("Crystallography"),
    549: _("Mineralogy"),
    550: _("Earth sciences"),
    551: _("Geology, hydrology, meteorology"),
    552: _("Petrology"),
    553: _("Economic geology"),
    554: _("Earth sciences of Europe"),
    555: _("Earth sciences of Asia"),
    556: _("Earth sciences of Africa"),
    557: _("Earth sciences of North America"),
    558: _("Earth sciences of South America"),
    559: _(
        "Earth sciences of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds"
    ),
    560: _("Paleontology"),
    561: _("Paleobotany, fossil microorganisms"),
    562: _("Fossil invertebrates"),
    563: _("Miscellaneous fossil marine and seashore invertebrates"),
    564: _("Fossil Mollusca and Molluscoidea"),
    565: _("Fossil Arthropoda"),
    566: _("Fossil Chordata"),
    567: _("Fossil cold-blooded vertebrates"),
    568: _("Fossil Aves (birds)"),
    569: _("Fossil Mammalia"),
    570: _("Biology"),
    571: _("Physiology and related subjects"),
    572: _("Biochemistry"),
    573: _("Specific physiological systems in animals, regional histology and physiology in animals"),
    574: _("Not assigned or no longer used"),
    575: _("Specific parts of and physiological systems in plants"),
    576: _("Genetics and evolution"),
    577: _("Ecology"),
    578: _("Natural history of organisms and related subjects"),
    579: _("Natural history of microorganisms, fungi, algae"),
    580: _("Plants"),
    581: _("Specific topics in natural history of plants"),
    582: _("Plants noted for specific vegetative characteristics and flowers"),
    583: _("Magnoliopsida (Dicotyledones)"),
    584: _("Liliopsida (Monocotyledones)"),
    585: _("Pinophyta (Gymnosperms)"),
    586: _("Cryptogamia (Seedless plants)"),
    587: _("Pteridophyta"),
    588: _("Bryophyta"),
    589: _("No longer used—formerly Forestry"),
    590: _("Animals"),
    591: _("Specific topics in natural history of animals"),
    592: _("Invertebrates"),
    593: _("Miscellaneous marine and seashore invertebrates"),
    594: _("Mollusca and Molluscoidea"),
    595: _("Arthropoda"),
    596: _("Chordata"),
    597: _("Cold-blooded vertebrates"),
    598: _("Aves (Birds)"),
    599: _("Mammalia (Mammals)"),
    600: _("Technology (Applied sciences)"),
    601: _("Philosophy and theory"),
    602: _("Miscellany"),
    603: _("Dictionaries, encyclopedias, concordances"),
    604: _("Technical drawing, hazardous materials technology; groups of people"),
    605: _("Serial publications"),
    606: _("Organizations"),
    607: _("Education, research, related topics"),
    608: _("Patents"),
    609: _("History, geographic treatment, biography"),
    610: _("Medicine and health"),
    611: _("Human anatomy, cytology, histology"),
    612: _("Human physiology"),
    613: _("Personal health and safety"),
    614: _("Forensic medicine; incidence of injuries, wounds, disease; public preventive medicine"),
    615: _("Pharmacology and therapeutics"),
    616: _("Diseases"),
    617: _("Surgery, regional medicine, dentistry, ophthalmology, otology, audiology"),
    618: _("Gynecology, obstetrics, pediatrics, geriatrics"),
    619: _("No longer used—formerly Experimental medicine"),
    620: _("Engineering and applied operations"),
    621: _("Applied physics"),
    622: _("Mining and related operations"),
    623: _("Military and nautical engineering"),
    624: _("Civil engineering"),
    625: _("Engineering of railroads, roads"),
    626: _("Not assigned or no longer used"),
    627: _("Hydraulic engineering"),
    628: _("Sanitary engineering"),
    629: _("Other branches of engineering"),
    630: _("Agriculture and related technologies"),
    631: _("Specific techniques; apparatus, equipment, materials"),
    632: _("Plant injuries, diseases, pests"),
    633: _("Field and plantation crops"),
    634: _("Orchards, fruits, forestry"),
    635: _("Garden crops (Horticulture)"),
    636: _("Animal husbandry"),
    637: _("Processing dairy and related products"),
    638: _("Insect culture"),
    639: _("Hunting, fishing, conservation, related technologies"),
    640: _("Home and family management"),
    641: _("Food and drink"),
    642: _("Meals and table service"),
    643: _("Housing and household equipment"),
    644: _("Household utilities"),
    645: _("Household furnishings"),
    646: _("Sewing, clothing, management of personal and family life"),
    647: _("Management of public households (Institutional housekeeping)"),
    648: _("Housekeeping"),
    649: _("Child rearing; home care of people with disabilities and illnesses"),
    650: _("Management and auxiliary services"),
    651: _("Office services"),
    652: _("Processes of written communication"),
    653: _("Shorthand"),
    654: _("Not assigned or no longer used"),
    655: _("Not assigned or no longer used"),
    656: _("Not assigned or no longer used"),
    657: _("Accounting"),
    658: _("General management"),
    659: _("Advertising and public relations"),
    660: _("Chemical engineering and related technologies"),
    661: _("Technology of industrial chemicals"),
    662: _("Technology of explosives, fuels, related products"),
    663: _("Beverage technology"),
    664: _("Food technology"),
    665: _("Technology of industrial oils, fats, waxes, gases"),
    666: _("Ceramic and allied technologies"),
    667: _("Cleaning, color, coating, related technologies"),
    668: _("Technology of other organic products"),
    669: _("Metallurgy"),
    670: _("Manufacturing"),
    671: _("Metalworking processes and primary metal products"),
    672: _("Iron, steel, other iron alloys"),
    673: _("Nonferrous metals"),
    674: _("Lumber processing, wood products, cork"),
    675: _("Leather and fur processing"),
    676: _("Pulp and paper technology"),
    677: _("Textiles"),
    678: _("Elastomers and elastomer products"),
    679: _("Other products of specific kinds of materials"),
    680: _("Manufacture of products for specific uses"),
    681: _("Precision instruments and other devices"),
    682: _("Small forge work (Blacksmithing)"),
    683: _("Hardware and household appliances"),
    684: _("Furnishings and home workshops"),
    685: _("Leather and fur goods, and related products"),
    686: _("Printing and related activities"),
    687: _("Clothing and accessories"),
    688: _("Other final products, and packaging technology"),
    689: _("Not assigned or no longer used"),
    690: _("Construction of buildings"),
    691: _("Building materials"),
    692: _("Auxiliary construction practices"),
    693: _("Construction in specific types of materials and for specific purposes"),
    694: _("Wood construction"),
    695: _("Roof covering"),
    696: _("Utilities"),
    697: _("Heating, ventilating, air-conditioning engineering"),
    698: _("Detail finishing"),
    699: _("Not assigned or no longer used"),
    700: _("The Arts"),
    701: _("Philosophy and theory of fine and decorative arts"),
    702: _("Miscellany of fine and decorative arts"),
    703: _("Dictionaries, encyclopedias, concordances of fine and decorative arts"),
    704: _("Special topics in fine and decorative arts"),
    705: _("Serial publications of fine and decorative arts"),
    706: _("Organizations and management of fine and decorative arts"),
    707: _("Education, research, related topics of fine and decorative arts"),
    708: _("Galleries, museums, private collections of fine and decorative arts"),
    709: _("History, geographic treatment, biography"),
    710: _("Area planning and landscape architecture"),
    711: _("Area planning (Civic art)"),
    712: _("Landscape architecture (Landscape design)"),
    713: _("Landscape architecture of trafficways"),
    714: _("Water features in landscape architecture"),
    715: _("Woody plants in landscape architecture"),
    716: _("Herbaceous plants in landscape architecture"),
    717: _("Structures in landscape architecture"),
    718: _("Landscape design of cemeteries"),
    719: _("Natural landscapes"),
    720: _("Architecture"),
    721: _("Architectural materials and structural elements"),
    722: _("Architecture from earliest times to c. 300"),
    723: _("Architecture from c. 300 to 1399"),
    724: _("Architecture from 1400"),
    725: _("Public structures"),
    726: _("Buildings for religious and related purposes"),
    727: _("Buildings for educational and research purposes"),
    728: _("Residential and related buildings"),
    729: _("Design and decoration of structures and accessories"),
    730: _("Sculpture and related arts"),
    731: _("Processes, forms, subjects of sculpture"),
    732: _("Sculpture from earliest times to c. 500, sculpture of non-literate peoples"),
    733: _("Greek, Etruscan, Roman sculpture"),
    734: _("Sculpture from ca 500 to 1399"),
    735: _("Sculpture from 1400"),
    736: _("Carving and carvings"),
    737: _("Numismatics and sigillography"),
    738: _("Ceramic arts"),
    739: _("Art metalwork"),
    740: _("Graphic arts"),
    741: _("Drawing and drawings"),
    742: _("Perspective in drawing"),
    743: _("Drawing and drawings by subject"),
    744: _("Communication design and visual design (proposed[5])"),
    745: _("Decorative arts"),
    746: _("Textile arts"),
    747: _("Interior decoration"),
    748: _("Glass"),
    749: _("Furniture and accessories"),
    750: _("Painting and paintings"),
    751: _("Techniques, procedures, apparatus, equipment, materials, forms"),
    752: _("Color"),
    753: _("Symbolism, allegory, mythology, legend"),
    754: _("Genre paintings"),
    755: _("Religion"),
    756: _("Not assigned or no longer used"),
    757: _("Human figures"),
    758: _("Nature, architectural subjects and cityscapes, other specific subjects"),
    759: _("History, geographic treatment, biography"),
    760: _("Printmaking and prints"),
    761: _("Relief processes (Block printing)"),
    762: _("Not assigned or no longer used"),
    763: _("Lithographic processes (Planographic processes)"),
    764: _("Chromolithography and serigraphy"),
    765: _("Metal engraving"),
    766: _("Mezzotinting, aquatinting, and related processes"),
    767: _("Etching and drypoint"),
    768: _("Not assigned or no longer used"),
    769: _("Prints"),
    770: _("Photography, computer art, cinematography, videography"),
    771: _("Techniques, procedures, apparatus, equipment, materials"),
    772: _("Metallic salt processes"),
    773: _("Pigment processes of printing"),
    774: _("No longer used—formerly Holography"),
    775: _("No longer used—formerly Digital photography"),
    776: _("Computer art (Digital art)"),
    777: _("Cinematography and Videography"),
    778: _("Specific fields and special kinds of photography"),
    779: _("Photographic images"),
    780: _("Music"),
    781: _("General principles and musical forms"),
    782: _("Vocal music"),
    783: _("Music for single voices"),
    784: _("Instruments and Instrumental ensembles and their music"),
    785: _("Ensembles with only one instrument per part"),
    786: _("Keyboard, mechanical, electrophonic, percussion instruments"),
    787: _("Stringed instruments (Chordophones)"),
    788: _("Wind instruments (Aerophones)"),
    789: _("Not assigned or no longer used"),
    790: _("Recreational and performing arts"),
    791: _("Public performances"),
    792: _("Stage presentations"),
    793: _("Indoor games and amusements"),
    794: _("Indoor games of skill"),
    795: _("Games of chance"),
    796: _("Athletic and outdoor sports and games"),
    797: _("Aquatic and air sports"),
    798: _("Equestrian sports and animal racing"),
    799: _("Fishing, hunting, shooting"),
    800: _("Literature (Belles-lettres) and rhetoric"),
    801: _("Philosophy and theory"),
    802: _("Miscellany"),
    803: _("Dictionaries, encyclopedias, concordances"),
    804: _("Not assigned or no longer used"),
    805: _("Serial publications"),
    806: _("Organizations and management"),
    807: _("Education, research, related topics"),
    808: _("Rhetoric and collections of literary texts from more than two literatures"),
    809: _("History, description, critical appraisal of more than two literatures"),
    810: _("American literature in English"),
    811: _("American poetry in English"),
    812: _("American drama in English"),
    813: _("American fiction in English"),
    814: _("American essays in English"),
    815: _("American speeches in English"),
    816: _("American letters in English"),
    817: _("American humor and satire in English"),
    818: _("American miscellaneous writings in English"),
    819: _("No longer used—formerly Puzzle activities"),
    820: _("English and Old English (Anglo-Saxon) literatures"),
    821: _("English Poetry"),
    822: _("English drama"),
    823: _("English fiction"),
    824: _("English essays"),
    825: _("English speeches"),
    826: _("English letters"),
    827: _("English humor and satire"),
    828: _("English miscellaneous writings"),
    829: _("Old English (Anglo-Saxon) literature"),
    830: _("German literature and literatures of related languages"),
    831: _("German poetry"),
    832: _("German drama"),
    833: _("German fiction"),
    834: _("German essays"),
    835: _("German speeches"),
    836: _("German letters"),
    837: _("German humor and satire"),
    838: _("German miscellaneous writings"),
    839: _("Other Germanic literatures"),
    840: _("French literature and literatures of related Romance languages"),
    841: _("French poetry"),
    842: _("French drama"),
    843: _("French fiction"),
    844: _("French essays"),
    845: _("French speeches"),
    846: _("French letters"),
    847: _("French humor and satire"),
    848: _("French miscellaneous writings"),
    849: _("Occitan, Catalan, Franco-Provençal literatures"),
    850: _("Literatures of Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican languages"),
    851: _("Italian poetry"),
    852: _("Italian drama"),
    853: _("Italian fiction"),
    854: _("Italian essays"),
    855: _("Italian speeches"),
    856: _("Italian letters"),
    857: _("Italian humor and satire"),
    858: _("Italian miscellaneous writings"),
    859: _("Literatures of Romanian, Rhaetian, Sardinian, Corsican languages"),
    860: _("Literatures of Spanish, Portuguese, Galician languages"),
    861: _("Spanish poetry"),
    862: _("Spanish drama"),
    863: _("Spanish fiction"),
    864: _("Spanish essays"),
    865: _("Spanish speeches"),
    866: _("Spanish letters"),
    867: _("Spanish humor and satire"),
    868: _("Spanish miscellaneous writings"),
    869: _("Literatures of Portuguese and Galician languages"),
    870: _("Latin literature and literatures of related Italic languages"),
    871: _("Latin poetry"),
    872: _("Latin dramatic poetry and drama"),
    873: _("Latin epic poetry and fiction"),
    874: _("Latin lyric poetry"),
    875: _("Latin speeches"),
    876: _("Latin letters"),
    877: _("Latin humor and satire"),
    878: _("Latin miscellaneous writings"),
    879: _("Literatures of other Italic languages"),
    880: _("Classical Greek literature and literatures of related Hellenic languages"),
    881: _("Classical Greek poetry"),
    882: _("Classical Greek drama"),
    883: _("Classical Greek epic poetry and fiction"),
    884: _("Classical Greek lyric poetry"),
    885: _("Classical Greek speeches"),
    886: _("Classical Greek letters"),
    887: _("Classical Greek humor and satire"),
    888: _("Classical Greek miscellaneous writings"),
    889: _("Modern Greek literature"),
    890: _("Literatures of other specific languages and language families"),
    891: _("East Indo-European and Celtic literatures"),
    892: _("Afro-Asiatic literatures"),
    893: _("Non-Semitic Afro-Asiatic literatures"),
    894: _(
        "Literatures of Altaic, Uralic, Hyperborean, Dravidian languages; literatures of miscellaneous languages of South Asia"
    ),
    895: _("Literatures of East and Southeast Asia"),
    896: _("African literatures"),
    897: _("Literatures of North American native languages"),
    898: _("Literatures of South American native languages"),
    899: _(
        "Literatures of non-Austronesian languages of Oceania, of Austronesian languages, of miscellaneous languages"
    ),
    900: _("History, geography, and auxiliary disciplines"),
    901: _("Philosophy and theory of history"),
    902: _("Miscellany of history"),
    903: _("Dictionaries, encyclopedias, concordances of history"),
    904: _("Collected accounts of events"),
    905: _("Serial publications of history"),
    906: _("Organizations and management of history"),
    907: _("Education, research, related topics of history"),
    908: _("History with respect to groups of people"),
    909: _("World history"),
    910: _("Geography and travel"),
    911: _("Historical geography"),
    912: _("Graphic representations of surface of earth and of extraterrestrial worlds"),
    913: _("Geography of and travel in the ancient world"),
    914: _("Geography of and travel in Europe"),
    915: _("Geography of and travel in Asia"),
    916: _("Geography of and travel in Africa"),
    917: _("Geography of and travel in North America"),
    918: _("Geography of and travel in South America"),
    919: _(
        "Geography of and travel in Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, and on extraterrestrial worlds"
    ),
    920: _("Biography, genealogy, insignia"),
    921: _("Biographies, shelved alphabetically by subject's last name."),
    922: _("Biographies, shelved alphabetically by subject's last name."),
    923: _("Biographies, shelved alphabetically by subject's last name."),
    924: _("Biographies, shelved alphabetically by subject's last name."),
    925: _("Biographies, shelved alphabetically by subject's last name."),
    926: _("Biographies, shelved alphabetically by subject's last name."),
    927: _("Biographies, shelved alphabetically by subject's last name."),
    928: _("Biographies, shelved alphabetically by subject's last name."),
    929: _("Genealogy, names, insignia"),
    930: _("History of ancient world to c. 499"),
    931: _("China to 420"),
    932: _("Egypt to 640"),
    933: _("Palestine to 70"),
    934: _("South Asia to 647"),
    935: _("Mesopotamia to 637 and Iranian Plateau to 637"),
    936: _("Europe north and west of Italian Peninsula to c. 499"),
    937: _("Italian Peninsula to 476 and adjacent territories to 476"),
    938: _("Greece to 323"),
    939: _("Other parts of ancient world"),
    940: _("History of Europe"),
    941: _("British Isles"),
    942: _("England and Wales"),
    943: _("Germany and neighboring central European countries"),
    944: _("France and Monaco"),
    945: _("Italy, San Marino, Vatican City, Malta"),
    946: _("Spain, Andorra, Gibraltar, Portugal"),
    947: _("Russia and neighboring east European countries"),
    948: _("Scandinavia"),
    949: _("Other parts of Europe"),
    950: _("History of Asia"),
    951: _("China and adjacent areas"),
    952: _("Japan"),
    953: _("Arabian Peninsula and adjacent areas"),
    954: _("India and neighboring south Asian countries;"),
    955: _("Iran"),
    956: _("Middle East (Near East)"),
    957: _("Siberia (Asiatic Russia)"),
    958: _("Central Asia"),
    959: _("Southeast Asia"),
    960: _("History of Africa"),
    961: _("Tunisia and Libya"),
    962: _("Egypt, Sudan, South Sudan"),
    963: _("Ethiopia and Eritrea"),
    964: _("Morocco, Ceuta, Melilla Western Sahara, Canary Islands"),
    965: _("Algeria"),
    966: _("West Africa and offshore islands"),
    967: _("Central Africa and offshore islands"),
    968: _("South Africa & southern Africa"),
    969: _("South Indian Ocean islands"),
    970: _("History of North America"),
    971: _("Canada"),
    972: _("Mexico, Central America, West Indies, Bermuda"),
    973: _("United States"),
    974: _("Northeastern United States (New England and Middle Atlantic states)"),
    975: _("Southeastern United States (South Atlantic states)"),
    976: _("South central United States"),
    977: _("North central United States"),
    978: _("Western United States"),
    979: _("Great Basin and Pacific Slope region of United States"),
    980: _("History of South America"),
    981: _("Brazil"),
    982: _("Argentina"),
    983: _("Chile"),
    984: _("Bolivia"),
    985: _("Peru"),
    986: _("Colombia and Ecuador"),
    987: _("Venezuela"),
    988: _("Guiana"),
    989: _("Paraguay and Uruguay"),
    990: _(
        "History of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds"
    ),
    991: _("Not assigned or no longer used"),
    992: _("Not assigned or no longer used"),
    993: _("New Zealand"),
    994: _("Australia"),
    995: _("New Guinea and neighboring countries of Melanesia"),
    996: _("Polynesia and other Pacific Ocean islands"),
    997: _("Atlantic Ocean islands"),
    998: _("Arctic islands and Antarctica"),
    999: _("Extraterrestrial worlds"),
}


def classification(number: Optional[int]) -> Optional[str] | StrPromise:
    """Full text of classification."""
    if not number:
        return None
    if number in CLASSIFICATION_DECIMAL_CLASSES:
        return CLASSIFICATION_DECIMAL_CLASSES[number]
    number = (number // 10) * 10
    if number in CLASSIFICATION_SUB_CLASSES:
        return CLASSIFICATION_SUB_CLASSES[number]
    number = (number // 100) * 100
    if number in CLASSIFICATION_CLASSES:
        return CLASSIFICATION_CLASSES[number]
    return f"Unknown skoufas classification number: {number}"
