# Generated by Django 6.0.6 on 2026-06-25 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.PositiveIntegerField(null=True, verbose_name="target object ID")),
                (
                    "merge_data",
                    models.JSONField(
                        help_text="Entity-specific snapshot of the deleted source object and all data needed to undo the merge.",
                        verbose_name="merge data",
                    ),
                ),
                ("merged_at", models.DateTimeField(auto_now_add=True, verbose_name="merged at")),
                ("undone_at", models.DateTimeField(blank=True, null=True, verbose_name="undone at")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merges_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="merged by",
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merges_undone",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="undone by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge log",
                "verbose_name_plural": "Merge logs",
                "ordering": ["-merged_at"],
                "permissions": [("can_curate", "Can curate catalog")],
            },
        ),
        migrations.CreateModel(
            name="SuppressedPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_a_id", models.PositiveIntegerField(verbose_name="object A ID")),
                ("object_b_id", models.PositiveIntegerField(verbose_name="object B ID")),
                ("suppressed_at", models.DateTimeField(auto_now_add=True, verbose_name="suppressed at")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "suppressed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="suppressed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suppressed pair",
                "verbose_name_plural": "Suppressed pairs",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_a_id", "object_b_id"), name="unique_suppressed_pair"
                    )
                ],
            },
        ),
    ]
