# Generated by Django 6.0.6 on 2026-06-27 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="started at")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="closed at")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_sessions",
                        to="books.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="started by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory session",
                "verbose_name_plural": "Inventory sessions",
                "ordering": ["-started_at"],
                "permissions": [("can_inventory", "Can perform inventory")],
            },
        ),
        migrations.CreateModel(
            name="InventorySessionEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scanned_at", models.DateTimeField(auto_now_add=True, verbose_name="scanned at")),
                (
                    "outcome",
                    models.CharField(
                        choices=[("confirmed", "Confirmed"), ("set_aside", "Set aside")],
                        max_length=20,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "entry_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_entries",
                        to="books.entrynumber",
                        verbose_name="entry number",
                    ),
                ),
                (
                    "previous_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_entries_from",
                        to="books.location",
                        verbose_name="previous location",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="curation.inventorysession",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory session entry",
                "verbose_name_plural": "Inventory session entries",
                "ordering": ["scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="MergeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.PositiveIntegerField(null=True, verbose_name="target object ID")),
                (
                    "merge_data",
                    models.JSONField(
                        help_text="Entity-specific snapshot of the deleted source object and all data needed to undo the merge.",
                        verbose_name="merge data",
                    ),
                ),
                ("merged_at", models.DateTimeField(auto_now_add=True, verbose_name="merged at")),
                ("undone_at", models.DateTimeField(blank=True, null=True, verbose_name="undone at")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merges_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="merged by",
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merges_undone",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="undone by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge log",
                "verbose_name_plural": "Merge logs",
                "ordering": ["-merged_at"],
                "permissions": [("can_curate", "Can curate catalog")],
            },
        ),
        migrations.CreateModel(
            name="SuppressedPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_a_id", models.PositiveIntegerField(verbose_name="object A ID")),
                ("object_b_id", models.PositiveIntegerField(verbose_name="object B ID")),
                ("suppressed_at", models.DateTimeField(auto_now_add=True, verbose_name="suppressed at")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "suppressed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="suppressed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suppressed pair",
                "verbose_name_plural": "Suppressed pairs",
            },
        ),
        migrations.AddConstraint(
            model_name="inventorysession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at", None)),
                fields=("location",),
                name="unique_open_inventory_session_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppressedpair",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_a_id", "object_b_id"), name="unique_suppressed_pair"
            ),
        ),
    ]
