#!/bin/bash

PROJECT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit; cd ..; pwd)"
cd "$PROJECT_DIR" || exit
pwd
rm -rf ./.venv
uv venv

# shellcheck disable=SC1091
source .venv/bin/activate
uv pip install -e '.[test]'
