#!/bin/bash

PROJECT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd)"
cd "$PROJECT_DIR"
pwd
rm db.sqlite3
rm -rf books/migrations/00*.py
rm -rf loaning/migrations/00*.py
. venv/bin/activate

skoufas-library makemigrations
skoufas-library migrate

skoufas-library createsuperuser --username admin --email a@a.com --noinput

skoufas-library dbfimport 2>junk/dbfimport-errors.log >junk/dbfimport.log
