#!/bin/bash

PROJECT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd)"
cd "$PROJECT_DIR"
pwd
mkdir -p junk
rm -f db.sqlite3
rm -rf books/migrations/00*.py
rm -rf loaning/migrations/00*.py
. venv/bin/activate

skoufas-library reset_db --no-input
skoufas-library makemigrations
skoufas-library migrate
skoufas-library installwatson

skoufas-library createsuperuser --username rockdreamer@gmail.com --email rockdreamer@gmail.com --noinput

skoufas-library dbfimport ../skoufas-dbf-reader/src/skoufas_dbf_reader/data/converted_entries.yml 2>junk/dbfimport-errors.log >junk/dbfimport.log
