#!/bin/bash

PROJECT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd)"
cd "$PROJECT_DIR"
pwd
. venv/bin/activate

skoufas-library makemessages -l el --ignore 'junk' --ignore manage.py --ignore venv
skoufas-library compilemessages
