#!/bin/bash

PROJECT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit; cd ..; pwd)"
cd "$PROJECT_DIR" || exit
pwd
# shellcheck disable=SC1091
. .venv/bin/activate
export PYTHONPATH=$PROJECT_DIR:$PYTHONPATH

skoufas-library makemessages -l el --ignore 'junk' --ignore manage.py --ignore .venv
skoufas-library compilemessages
